import Layout from "@/components/Layout";
import Navbar from "@/components/Navbar";
import HeroSection from "@/sections/HeroSection";
import AboutSection from "@/sections/AboutSection";
import ServicesSection from "@/sections/ServicesSection";
import TestimonialsSection from "@/sections/TestimonialsSection";
import GallerySection from "@/sections/GallerySection";
import BusinessOverviewSection from "@/sections/BusinessOverviewSection";
import FAQSection from "@/sections/FAQSection";
import ServiceAreasSection from "@/sections/ServiceAreasSection";
import ServiceHighlightsSection from "@/sections/ServiceHighlightsSection";
import FooterSection from "@/sections/FooterSection";
import CTASection from "@/sections/CTASection";
import { LandingPageData } from "@/types/template";
import CompanyDetails from "@/sections/CompanyDetails";
import { getLandingPageData } from "@/lib/data";
import { notFound } from "next/navigation";
import { Metadata } from "next";

// Enable ISR with 60-second revalidation
export const revalidate = 60;

// Generate static params for all published landing pages
export async function generateStaticParams() {
  // For now, we'll use the environment variables to generate the single page
  // In the future, this could be expanded to generate multiple pages
  const templateId = process.env.NEXT_PUBLIC_TEMPLATE_ID;
  const id = process.env.NEXT_PUBLIC_ID;
  
  if (!templateId || !id) {
    console.warn('Missing NEXT_PUBLIC_TEMPLATE_ID or NEXT_PUBLIC_ID environment variables');
    return [];
  }

  return [{ templateId, id }];
}

// Server-side data fetching for SSG
async function getLandingPageDataForPage(): Promise<LandingPageData> {
  const landingPageData = await getLandingPageData();

  if (!landingPageData) {
    notFound();
  }

  return landingPageData;
}

// Generate metadata for Next.js App Router
export async function generateMetadata(): Promise<Metadata> {
  const landingPageData = await getLandingPageData();
  if (!landingPageData) {
    return {
      title: "Create Next App",
      description: "Generated by create next app",
    };
  }
  
  // Override with the provided meta title and description
  const title = "Hire Now Certified Drywall, Painting & Basement Refinishing Service Contractor Maryland | Star Quality Group";
  const description = "Looking for drywall, painting, or basement remodeling? Star Quality Group delivers high quality renovation services at affordable prices. Choose professionals with 10+ years of experience. Call now for a free estimate today!";
  
  const businessName = landingPageData.businessName || 'Star Quality Group';
  const images = landingPageData.images;
  const logoImage = images?.find((img) => img.slotName === 'logo-image')?.imageUrl;
  const heroImage = images?.find((img) => img.slotName === 'hero-image-1' || img.category === 'hero')?.imageUrl;
  const ogImage = logoImage || heroImage;

  return {
    title,
    description,
    
    // Open Graph
    openGraph: {
      title,
      description,
      url: 'https://www.starqualitygroup.com',
      siteName: businessName,
      images: ogImage ? [{
        url: ogImage,
        alt: `${businessName} - ${title}`,
      }] : [],
      locale: 'en_US',
      type: 'website',
    },
    
    // Twitter
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: ogImage ? [ogImage] : [],
    },
    
    // Additional metadata
    alternates: {
      canonical: 'https://www.starqualitygroup.com',
    },
    
    // Verification and other meta tags
    other: {
      'theme-color': landingPageData.themeData?.primaryColor,
      'focused-keywords': landingPageData.seoData?.focusedKeywords?.join(', ') || '',
    },
  };
}

export default async function Home() {
  const landingPageData = await getLandingPageDataForPage();

  return (
    <Layout
      title={landingPageData.seoData.title}
      description={landingPageData.seoData.description}
      theme={landingPageData.themeData}
      seoData={landingPageData.seoData}
      landingPageData={landingPageData}
    >
        <Navbar
          businessName={landingPageData.businessName}
          logoImage="/logo.png"
          themeData={landingPageData.themeData}
          phoneNumber={landingPageData.businessData?.phone}
        />
        <div
          style={{
            ['--color-primary' as string]: landingPageData.themeData?.primaryColor,
            ['--color-secondary' as string]: landingPageData.themeData?.secondaryColor,
            ['--color-accent' as string]: landingPageData.themeData?.accentColor ?? landingPageData.themeData?.primaryColor,
            ['--background' as string]: '#ffffff',
            ['--foreground' as string]: '#171717',
            ['--color-surface' as string]: '#ffffff',
            ['--color-text' as string]: '#171717',
          }}
        >
          <main>
          {landingPageData.content.hero && (
            <HeroSection 
              title={landingPageData.content.hero.title}
              subtitle={landingPageData.content.hero.subtitle}
              description={landingPageData.content.hero.description}
              ctaButton={landingPageData.content.hero.ctaButton ?? { href: '#contact', label: 'Contact Us' }}
              images={landingPageData.images}
              themeData={landingPageData.themeData}
            />
          )}

          {landingPageData.content.serviceHighlights && (
            <ServiceHighlightsSection 
              data={landingPageData.content.serviceHighlights}
              theme={landingPageData.themeData}
            />
          )}

          {landingPageData.content.about && (
            <AboutSection 
              title={landingPageData.content.about.title}
              description={landingPageData.content.about.description}
              features={landingPageData.content.about.features}
              ctaButton={landingPageData.content.about.ctaButton ?? { href: '/about-us', label: 'Get in touch' }}
              images={landingPageData.images}
              theme={landingPageData.themeData}
            />
          )}

          {landingPageData.content.companyDetails && (
            <CompanyDetails 
              data={landingPageData.content.companyDetails}
              images={landingPageData.images}
              theme={landingPageData.themeData}
            />
          )}
{landingPageData.content.ctaSection && (
            <CTASection 
              data={landingPageData.content.ctaSection}
              theme={landingPageData.themeData}
              images={landingPageData.images}
            />
          )}
          {landingPageData.content.services && (
            <ServicesSection
              title={landingPageData.content.services.title}
              description={landingPageData.content.services.description}
              services={landingPageData.content.services.services}
              images={landingPageData.images ?? []}
              theme={landingPageData.themeData}
            />
          )}

         

          {landingPageData.content.testimonials && (
            <TestimonialsSection 
              title={landingPageData.content.testimonials.title}
              description={landingPageData.content.testimonials.description}
              testimonials={landingPageData.content.testimonials.testimonials}
              theme={landingPageData.themeData}
            />
          )}

          

          {landingPageData.content.gallery && (
            <GallerySection 
              title={landingPageData.content.gallery.title}
              description={landingPageData.content.gallery.description}
              images={landingPageData.images}
              theme={landingPageData.themeData}
            />
          )}

          {landingPageData.content.businessOverview && (
            <BusinessOverviewSection />
          )}

          {landingPageData.content.faq && (
            <FAQSection 
              title={landingPageData.content.faq.title}
              description={landingPageData.content.faq.description}
              questions={landingPageData.content.faq.questions}
              themeData={landingPageData.themeData}
            />
          )}

          {landingPageData.businessData.serviceAreas &&
            landingPageData.businessData.serviceAreas.length > 0 && (
              <ServiceAreasSection 
                serviceAreas={landingPageData.businessData.serviceAreas}
                themeData={landingPageData.themeData}
              />
            )}

          <FooterSection 
            footerTitle={landingPageData.seoData.title}
            socialsList={(landingPageData.businessData.socialLinks || []).map(s => ({ name: s.platform, url: s.url }))}
            originCity={landingPageData.businessData.address?.city || ''}
            workingScope={landingPageData.businessData.serviceAreas && landingPageData.businessData.serviceAreas.length
              ? `serving ${Array.from(new Set(landingPageData.businessData.serviceAreas.map(a => a.region))).filter(r => r && r !== 'DC').join(', ')}`
              : ''}
            contactEmail={landingPageData.businessData.email}
            agencyName={landingPageData.businessName}
            currentYear={new Date().getFullYear()}
            themeData={landingPageData.themeData}
            businessName={landingPageData.businessName}
            businessData={landingPageData.businessData}
          />
        </main>

       
      </div>
    </Layout>
  );
}
